pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('dockerhub')    // ID must match Jenkins credentials ID
        DOCKERHUB_REPO = "bhangdawon/djangoapp"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Set Version') {
            steps {
                script {
                    def VERSION = "v${BUILD_NUMBER}"
                    env.IMAGE_TAG = "${DOCKERHUB_REPO}:${VERSION}"
                    echo "Docker Image Tag → ${IMAGE_TAG}"
                }
            }
        }

        stage('Docker Login') {
            steps {
                sh """
                echo "${DOCKERHUB_PSW}" | docker login -u "${DOCKERHUB_USR}" --password-stdin
                """
            }
        }

        stage('Docker Build') {
            steps {
                sh """
                docker build -t ${IMAGE_TAG} .
                """
            }
        }

        stage('Docker Push') {
            steps {
                sh "docker push ${IMAGE_TAG}"
            }
        }

        stage('K8S Deploy') {
            steps {
                sh 'kubectl apply -f ~/django_git/yaml/mysql-pv.yaml'
                sh 'kubectl apply -f ~/django_git/yaml/mysql-pvc.yaml'
                sh 'kubectl apply -f ~/django_git/yaml/mysql-deployment.yaml'
                sh 'kubectl apply -f ~/django_git/yaml/mysql-service.yaml'
                sh 'kubectl apply -f ~/django_git/yaml/django-deployment.yaml'
                sh 'kubectl apply -f ~/django_git/yaml/django-service.yaml'
                sh 'kubectl apply -f ~/django_git/yaml/ingress.yaml'
            }
        }
    }

    post {
        success {
            echo "🎉 성공! DockerHub Push + Kubernetes Deploy 완료!"
        }
        cleanup {
            sh "docker system prune -af"   // Optional cleanup
        }
    }
}

