apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-nfs
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: mysql-pv-nfs

